discord_token: "YOUR_DISCORD_TOKEN"
gateway_intents:
  - "GUILDS"
  - "GUILD_VOICE_STATES"
  - "GUILD_MESSAGES"
  - "MESSAGE_CONTENT"
dummy_message: "ちくわ大明神。"
ffmpeg_path: "/usr/bin/ffmpeg"
ffmpeg_options: [
  "-i", "pipe:0",
  "-ac", "2",
  "-ar", "48000",
  "-f", "s16le",
  "-loglevel", "quiet",
  "pipe:1"
]
message_length_limit: 100
ms_before_leave: 5000
prompt_regex: '^!ymr\s+(.+)$'
template_text_message:
  summon: "{{ channel_name }}に参加します。"
  summon_but_already_joined: "すでにボイスチャネルに参加しています。"
  summon_not_from_vc: "ボイスチャネルに入ってから呼んでください。"
  unsummon: "ボイスチャネルを離れます。"
  unsummon_not_from_same_vc: "同じボイスチャネルから呼んでください。"
  unsummon_not_joined: "まだボイスチャネルに入っていません。"
  help: |-
    Daidoquer2 v#{{ version }}

    /join  Join the VC
    /leave Leave the VC
    /help  Show this help
template_voice_message:
  i_joined: "こんにちは、yomerです。やさしくしてね。"
  im_leaving: "。お相手はyomerでした。またね。"
  joined: "{{ user_name }}さんが参加しました。"
  left: "{{ user_name }}さんが離れました。"
  started_live: "{{ user_name }}さんがライブを始めました。"
  stopped_live: "{{ user_name }}さんがライブを終了しました。"
  created_thread: "{{ user_name }}さんがスレッド「{{ thread_name }}」を作りました。"
announcer: "結月ゆかり"
voices:
  "結月ゆかり":
    provider: ["post", "http://localhost:8400"]
    available_via_role: false
  "四国めたん":
    provider: ["su_shiki_com", "speaker=2"]
  "ずんだもん":
    provider: ["su_shiki_com", "speaker=3"]
  "春日部つむぎ":
    provider: ["su_shiki_com", "speaker=8"]
  "雨晴はう":
    provider: ["su_shiki_com", "speaker=10"]
  "波音リツ":
    provider: ["su_shiki_com", "speaker=9"]
  "玄野武宏":
    provider: ["su_shiki_com", "speaker=11"]
  "青山龍星":
    provider: ["su_shiki_com", "speaker=13"]
  "冥鳴ひまり":
    provider: ["su_shiki_com", "speaker=14"]
  "九州そら":
    provider: ["su_shiki_com", "speaker=16"]
  "もち子さん":
    provider: ["su_shiki_com", "speaker=20"]
  "剣崎雌雄":
    provider: ["su_shiki_com", "speaker=21"]
  "WhiteCUL":
    provider: ["su_shiki_com", "speaker=23"]
  "No.7":
    provider: ["su_shiki_com", "speaker=29"]
  "ちび式じい":
    provider: ["su_shiki_com", "speaker=42"]
  "櫻歌ミコ":
    provider: ["su_shiki_com", "speaker=43"]
  "小夜/SAYO":
    provider: ["su_shiki_com", "speaker=46"]
  "ナースロボ＿タイプＴ":
    provider: ["su_shiki_com", "speaker=47"]
  "†聖騎士 紅桜†":
    provider: ["su_shiki_com", "speaker=51"]
  "雀松朱司":
    provider: ["su_shiki_com", "speaker=52"]
  "麒ヶ島宗麟":
    provider: ["su_shiki_com", "speaker=53"]
  "春歌ナナ":
    provider: ["su_shiki_com", "speaker=54"]
  "猫使アル":
    provider: ["su_shiki_com", "speaker=55"]
  "猫使ビィ":
    provider: ["su_shiki_com", "speaker=58"]
  "中国うさぎ":
    provider: ["su_shiki_com", "speaker=61"]
  "栗田まろん":
    provider: ["su_shiki_com", "speaker=67"]
  "あいえるたん":
    provider: ["su_shiki_com", "speaker=68"]
  "満別花丸":
    provider: ["su_shiki_com", "speaker=69"]
  "琴詠ニア":
    provider: ["su_shiki_com", "speaker=74"]
